server:
  port: 8189
  servlet:
    context-path: /market
spring:
  application:
    name: front-service
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
